aapiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: ghcr.io/spencerjirehcebrian/quantum-cash-digital-wallet-account-service:latest
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: springboot-env-secret
      imagePullSecrets:
      - name: github-registry