
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP