server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quantumcashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/quantumcashdb
    user: postgres
    password: postgres
    schemas: user_service
    repair-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: your-issuer-uri

payment_gateway:
  service:
    url: http://localhost:8085

notification:
  service:
    url: http://localhost:8086
