server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/quantumcashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://postgres-service:5432/quantumcashdb
    user: postgres
    password: postgres
    schemas: user_service
    repair-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

payment_gateway:
  service:
    url: http://localhost:8085

notification:
  service:
    url: http://localhost:8086
