apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      json.keys_under_root: true
      json.add_error_key: true
      paths:
        - /app/logs/*.json
    output.logstash:
      hosts: ["logstash-logstash:5044"]